Repository captures-2024/soongan-android, pull requests merged in 2025-01, with the labels that each got.

#54 [SG-80] bottom bar flicker 이슈
  core/designSystem/src/main/kotlin/com/captures2024/soongan/core/designsystem/theme/Dimensions.kt
  core/designSystem/src/main/kotlin/com/captures2024/soongan/core/designsystem/util/ModifierExt.kt
  feature/awards/src/main/kotlin/com/captures2024/soongan/feature/awards/route/AwardsRoute.kt
  feature/feed/src/main/kotlin/com/captures2024/soongan/feature/feed/route/FeedRoute.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/route/HomeRoute.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/post/HomePostScreenBottomBar.kt
  feature/main/src/main/kotlin/com/captures2024/soongan/feature/main/navigation/MainRouteNavHost.kt
  feature/main/src/main/kotlin/com/captures2024/soongan/feature/main/ui/MainScreen.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/route/ProfileRoute.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/profile/ProfileScreen.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/profile/ProfileScreenHeader.kt
Labels: bug, refactor

#55 [SG-83] home api
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/di/RemoteDataSourceModule.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/di/ServiceModule.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/mapper/HomeMapper.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/remote/HomeDataSource.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/remote/impl/HomeDataSourceImpl.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/HomeRepository.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/impl/HomeRepositoryImpl.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/service/HomeService.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/home/GetHomeUseCase.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/ContestInfoDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/PostInfoDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/home/GetHomeStatusContestInfoResponse.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/home/GetHomeStatusPostInfoResponse.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/home/GetHomeStatusResponse.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/home/HomePostNavigator.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/HomePostViewModel.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/HomeViewModel.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/route/HomeRoute.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/state/home/HomeIntent.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/state/home/HomeSideEffect.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/state/home/HomeUIState.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/home/HomeScreenBody.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/home/HomeScreenTopBar.kt
  feature/main/src/main/kotlin/com/captures2024/soongan/feature/main/navigation/MainRouteNavHost.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/navigation/ProfileNavigation.kt
Labels: enhancement

#56 [SG-81] profile connect api
  core/common/src/main/kotlin/com/captures2024/soongan/core/common/Validation.kt
  core/data/build.gradle.kts
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/mapper/MembersMapper.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/remote/MembersDataSource.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/remote/impl/MembersDataSourceImpl.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/MembersRepository.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/utils/MultiPartExt.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/utils/UriUtil.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/members/PatchProfileUseCase.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/UserProfile.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/members/GetMemberInfoResponse.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/profile/EditProfileNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/profile/ProfileNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/profile/ProfileRootNavigator.kt
  feature/main/src/main/kotlin/com/captures2024/soongan/feature/main/navigation/MainRouteNavHost.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/EditProfileViewModel.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ProfileViewModel.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/navigation/ProfileMenuItem.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/navigation/ProfileNavigation.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/route/EditProfileRoute.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/route/ProfileRoute.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/state/edit/EditProfileIntent.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/state/edit/EditProfileSideEffect.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/state/edit/EditProfileUIState.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/state/profile/ProfileIntent.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/state/profile/ProfileSideEffect.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/state/profile/ProfileUIState.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/edit/EditProfileScreen.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/edit/EditProfileScreenBody.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/edit/component/ProfileOutlinedTextField.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/profile/ProfileScreenHeader.kt
  feature/profile/src/main/res/values/strings.xml
  feature/signUp/src/main/kotlin/com/captures2024/soongan/feature/signUp/NicknameViewModel.kt
Labels: enhancement, refactor

#57 [SG-82] 사진 게시글 등록 API 연결
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/di/RemoteDataSourceModule.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/di/ServiceModule.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/mapper/WeeklyContestMapper.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/remote/WeeklyContestDataSource.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/remote/impl/WeeklyContestDataSourceImpl.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/WeeklyContestRepository.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/impl/WeeklyContestRepositoryImpl.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/service/WeeklyContestService.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/weekly/contests/RegisterPostUseCase.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/PostInfoDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/weekly/contests/RegisterPostResponse.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/RegistrationPostViewModel.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/route/HomeRoute.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/registration_post/RegistrationPostScreen.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/registration_post/RegistrationPostScreenTopBar.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/registration_post/TilteInpuEditText.kt
Labels: enhancement

#58 [SG-85] 게시글 조회
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/mapper/WeeklyContestMapper.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/remote/WeeklyContestDataSource.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/remote/impl/WeeklyContestDataSourceImpl.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/WeeklyContestRepository.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/impl/WeeklyContestRepositoryImpl.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/service/WeeklyContestService.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/weekly/contests/GetGalleryUseCase.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/GalleryDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/weekly/contests/GetGalleryPageInfoResponse.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/weekly/contests/GetGalleryPostInfoResponse.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/weekly/contests/GetGalleryResponse.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/HomeGalleryViewModel.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/route/HomeGalleryRoute.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/state/home/HomeUIState.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/state/home_gallery/HomeGalleryIntent.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/state/home_gallery/HomeGalleryUIState.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/gallery/HomeGalleryBottomSheet.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/gallery/HomeGalleryScreen.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/gallery/component/HomeGalleryItems.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/gallery/component/HomeGalleryTopBar.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/utils/GalleryPhotoSortFilter.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/utils/PaginationStatus.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/utils/PostOrderType.kt
Labels: enhancement, refactor

#60 [SG-93] Base VM 리펙터 && 전역 loading 관리 구현
  app/src/main/kotlin/com/captures2024/soongan/SoonGanActivity.kt
  app/src/main/kotlin/com/captures2024/soongan/route/AppRoute.kt
  core/common/build.gradle.kts
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/LoadingRepository.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/MembersRepository.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/impl/LoadingRepositoryImpl.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/impl/MembersRepositoryImpl.kt
  core/domain/build.gradle.kts
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/loading/ClearLoadingUseCase.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/loading/GetLoadingFlowUseCase.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/loading/HideLoadingUseCase.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/loading/IsLoadingUseCase.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/loading/ShowLoadingUseCase.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/members/GetCurrentMemberFlow.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/members/GetGuestModeFlowUseCase.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/members/SetGuestModeUseCase.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/AppRootViewModel.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/NewBaseViewModel.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/home/HomeGalleryViewModel.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/home/HomePostPhotoViewModel.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/home/HomePostViewModel.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/home/HomeViewModel.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/sign/SignViewModel.kt
  feature/sign/src/main/kotlin/com/captures2024/soongan/feature/sign/navigation/SignRouteNavhost.kt
  feature/signIn/src/main/kotlin/com/captures2024/soongan/feature/signIn/route/SignInRoute.kt
  feature/signUp/src/main/kotlin/com/captures2024/soongan/feature/signUp/BirthViewModel.kt
  feature/signUp/src/main/kotlin/com/captures2024/soongan/feature/signUp/navigation/SignUpNavigation.kt
  feature/signUp/src/main/kotlin/com/captures2024/soongan/feature/signUp/route/InputBirthRoute.kt
  feature/signUp/src/main/kotlin/com/captures2024/soongan/feature/signUp/state/birth/BirthSideEffect.kt
Labels: refactor

#62 [SG-94] refactor profile vm
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/MembersRepository.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/impl/MembersRepositoryImpl.kt
  core/designSystem/src/main/kotlin/com/captures2024/soongan/core/designsystem/component/NonScaleText.kt
  core/designSystem/src/main/kotlin/com/captures2024/soongan/core/designsystem/component/SoonGanButton.kt
  core/designSystem/src/main/kotlin/com/captures2024/soongan/core/designsystem/component/gallery/SoonGanGallery.kt
  core/designSystem/src/main/kotlin/com/captures2024/soongan/core/designsystem/component/gallery/SoonGanGalleryItems.kt
  core/designSystem/src/main/kotlin/com/captures2024/soongan/core/designsystem/component/nonScaleStyle.kt
  core/designSystem/src/main/kotlin/com/captures2024/soongan/core/designsystem/util/TextUnitExtension.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/auth/SignOutSocialPlatformUseCase.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/auth/WithdrawMemberUseCase.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/members/ClearCurrentMemberUseCase.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/members/GetCurrentMemberFlowUseCase.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/profile/ProfileEditNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/profile/ProfileNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/profile/ProfileRootNavigator.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/AppRootViewModel.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/model/profile/EditingProfileState.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/model/profile/ProfileBtmShtCheckType.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/model/profile/ProfileBtmShtDepthState.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/model/profile/ProfileBtmShtMenuItem.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/model/profile/ProfileBtmShtOutType.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/model/profile/PushSettingState.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/model/profile/PushSettingType.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/model/profile/UserProfile.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/profile/ProfileBtmShtViewModel.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/profile/ProfileEditViewModel.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/profile/ProfileViewModel.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/state/home_gallery/HomeGalleryIntent.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/state/home_gallery/HomeGallerySideEffect.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/state/home_gallery/HomeGalleryUIState.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/gallery/HomeGalleryScreen.kt
  feature/main/src/main/kotlin/com/captures2024/soongan/feature/main/navigation/MainRouteNavHost.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ProfileViewModel.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/navigation/ProfileMenuItem.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/navigation/ProfileNavigation.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/route/EditProfileRoute.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/route/ProfileRoute.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/state/profile/ProfileIntent.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/state/profile/ProfileSideEffect.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/state/profile/ProfileUIState.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/edit/EditProfileBottomSheet.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/edit/EditProfileScreen.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/edit/EditProfileScreenBody.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/edit/component/EditProfileButton.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/edit/component/ProfileOutlinedTextField.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/profile/ProfileMenuBottomSheet.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/profile/ProfileScreen.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/profile/ProfileScreenBody.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/profile/ProfileScreenHeader.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/profile/bottomSheet/ProfileBottomSheet.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/profile/bottomSheet/ProfileBottomSheetMenuItems.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/profile/bottomSheet/component/ItemText.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/profile/bottomSheet/component/ItemTopBar.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/profile/bottomSheet/component/MenuItemTextField.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/utils/ProfileMenuItemExt.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/utils/PushSettingTypeExt.kt
  feature/profile/src/main/res/values/strings.xml
Labels: enhancement, refactor

#63 [SG-96] 공통 Dialog
  app/src/main/kotlin/com/captures2024/soongan/SoonGanActivity.kt
  core/designSystem/src/main/kotlin/com/captures2024/soongan/core/designsystem/component/SGDefaultDialog.kt
  core/designSystem/src/main/kotlin/com/captures2024/soongan/core/designsystem/component/SoonGanButton.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/home/HomeViewModel.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/post/RegistrationPostViewModel.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/RegistrationPostViewModel.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/route/RegistrationPostRoute.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/state/registration_post/RegistrationPostIntent.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/state/registration_post/RegistrationPostUIState.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/registration_post/RegistrationPostScreen.kt
  feature/home/src/main/kotlin/com/captures2024/soongan/feature/home/ui/registration_post/SubmitBottomSheetDialog.kt
  feature/main/src/main/kotlin/com/captures2024/soongan/feature/main/ui/SoonGanBottomBar.kt
Labels: enhancement

#64 [fix] navigate 오류 수정
  app/src/main/kotlin/com/captures2024/soongan/SoonGanActivity.kt
  app/src/main/kotlin/com/captures2024/soongan/route/AppRoute.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/welcome/WelcomeNavigator.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/welcome/WelcomeViewModel.kt
  feature/main/src/main/kotlin/com/captures2024/soongan/feature/main/navigation/MainRouteNavHost.kt
  feature/main/src/main/kotlin/com/captures2024/soongan/feature/main/route/MainRoute.kt
  feature/main/src/main/kotlin/com/captures2024/soongan/feature/main/route/MainRouteState.kt
  feature/main/src/main/kotlin/com/captures2024/soongan/feature/main/ui/MainScreen.kt
  feature/welcome/src/main/kotlin/com/captures2024/soongan/feature/welcome/WelcomeViewModel.kt
  feature/welcome/src/main/kotlin/com/captures2024/soongan/feature/welcome/navigation/WelcomeNavigation.kt
  feature/welcome/src/main/kotlin/com/captures2024/soongan/feature/welcome/route/WelcomeRoute.kt
  feature/welcome/src/main/kotlin/com/captures2024/soongan/feature/welcome/state/WelcomeIntent.kt
  feature/welcome/src/main/kotlin/com/captures2024/soongan/feature/welcome/state/WelcomeSideEffect.kt
  feature/welcome/src/main/kotlin/com/captures2024/soongan/feature/welcome/state/WelcomeUIState.kt
  feature/welcome/src/main/kotlin/com/captures2024/soongan/feature/welcome/ui/WelcomeScreen.kt
Labels: bug
