Repository captures-2024/soongan-android, pull requests merged in 2025-08, with the labels that each got.

#136 [SG-162] 피드 화면 수정
  design/svg/icon_non_fill_down_arrow.svg
  presentation/designSystem/icon/src/main/kotlin/com/captures2024/soongan/presentation/designsystem/icon/IconPreview.kt
  presentation/designSystem/icon/src/main/kotlin/com/captures2024/soongan/presentation/designsystem/icon/__MyIconPack.kt
  presentation/designSystem/icon/src/main/kotlin/com/captures2024/soongan/presentation/designsystem/icon/myiconpack/IconNonFillDownArrow.kt
  presentation/designSystem/ui/src/main/kotlin/com/captures2024/soongan/presentation/designsystem/ui/component/gallery/SGGallery.kt
  presentation/designSystem/ui/src/main/kotlin/com/captures2024/soongan/presentation/designsystem/ui/component/gallery/SGGalleryHeader.kt
  presentation/feature/main-feed/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/feed/component/feed/FeedGalleryHeaderComponent.kt
  presentation/feature/main-post/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/post/component/info/PostInfoTopBarComponent.kt
  presentation/feature/main-post/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/post/component/screen/PostInfoEditScreen.kt
  presentation/feature/main-post/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/post/component/screen/PostInfoScreen.kt
  presentation/feature/main-post/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/post/route/PostInfoEditRoute.kt
  presentation/feature/main-post/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/post/route/PostInfoRoute.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/feed/FeedViewModel.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/post/PostInfoEditViewModel.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/post/PostInfoViewModel.kt
Labels: refactor

#137 [SG-122] 소명하기 구현
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/request/report/PostExplainRequest.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/profile/CompleteExplainNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/profile/ExplainNavigator.kt
  data/repository/report-impl/src/main/kotlin/com/captures2024/soongan/data/repository/report/impl/ReportRepositoryImpl.kt
  data/service/api/src/main/kotlin/com/captures2024/soongan/data/service/api/ReportAPI.kt
  data/source/report-impl/src/main/kotlin/com/captures2024/soongan/data/source/report/impl/remote/ReportRemoteDataSourceImpl.kt
  data/source/report/src/main/kotlin/com/captures2024/soongan/data/source/report/remote/ReportRemoteDataSource.kt
  domain/repository/report/src/main/kotlin/com/captures2024/soongan/domain/repository/report/ReportRepository.kt
  domain/usecase/module/src/main/kotlin/com/captures2024/soongan/domain/usecase/module/ReportUseCaseModule.kt
  domain/usecase/report-impl/src/main/kotlin/com/captures2024/soongan/domain/usecase/report/impl/PostExplainUseCaseImpl.kt
  domain/usecase/report/src/main/kotlin/com/captures2024/soongan/domain/usecase/report/PostExplainUseCase.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/component/screen/CompleteExplainScreen.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/component/screen/ExplainScreen.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/navigation/MainProfileNavigation.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/route/CompleteExplainRoute.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/route/ExplainRoute.kt
  presentation/feature/main-profile/src/main/res/values/strings.xml
  presentation/feature/main/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/component/screen/MainScreen.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/profile/ExplainViewModel.kt
Labels: enhancement

#145 [SG-172] 회차 관련 문제 수정
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/feed/FeedNavigator.kt
  presentation/feature/main-awards/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/awards/component/info/AwardsInfoComponent.kt
  presentation/feature/main-awards/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/awards/component/screen/AwardsInfoScreen.kt
  presentation/feature/main-awards/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/awards/navigation/MainAwardsNavigation.kt
  presentation/feature/main-awards/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/awards/route/AwardsInfoRoute.kt
  presentation/feature/main/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/component/SoonGanBottomBar.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/award/AwardsInfoViewModel.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/feed/FeedViewModel.kt
Labels: bug, enhancement

#143 [SG-156] 프로필 탭 수정
  presentation/feature/main-feed/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/feed/component/screen/FeedScreen.kt
  presentation/feature/main-home/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/home/component/screen/HomeGalleryScreen.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/component/profile/ProfileBodyComponent.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/component/profile/ProfileEditBodyComponent.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/component/profile/ProfileTopBarComponent.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/component/screen/ProfileEditScreen.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/component/screen/ProfileScreen.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/profile/ProfileEditViewModel.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/profile/ProfileViewModel.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/model/PaginationStatus.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/model/UserProfile.kt
Labels: enhancement
