Repository captures-2024/soongan-android, pull requests merged in 2025-07, with the labels that each got.

#116 [Modify] 콘테스트 리스트 조회 Response 변경
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/weekly/contests/GetWeeklyContestInfoResponse.kt
  data/source/contest-impl/src/main/kotlin/com/captures2024/soongan/data/source/contest/impl/mapper/GetWeeklyContestInfoResponse.kt
Labels: enhancement

#117 [SG-139] 알림 api 연결
  core/common/src/main/kotlin/com/captures2024/soongan/core/common/permission/Context.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/NotificationSettingDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/request/notifications/PatchNotificationSettingsRequest.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/notifications/GetNotificationSettingsResponse.kt
  data/repository/notification-impl/src/main/kotlin/com/captures2024/soongan/data/repository/notification/impl/NotificationRepositoryImpl.kt
  data/service/api/src/main/kotlin/com/captures2024/soongan/data/service/api/NotificationsAPI.kt
  data/source/notification-impl/src/main/kotlin/com/captures2024/soongan/data/source/notification/impl/mapper/GetNotificationSettingsResponse.kt
  data/source/notification-impl/src/main/kotlin/com/captures2024/soongan/data/source/notification/impl/mapper/PatchNotificationSettingsRequest.kt
  data/source/notification-impl/src/main/kotlin/com/captures2024/soongan/data/source/notification/impl/remote/NotificationsRemoteDataSourceImpl.kt
  data/source/notification/src/main/kotlin/com/captures2024/soongan/data/source/notification/remote/NotificationsRemoteDataSource.kt
  domain/repository/notification/src/main/kotlin/com/captures2024/soongan/domain/repository/notification/NotificationRepository.kt
  domain/usecase/module/src/main/kotlin/com/captures2024/soongan/domain/usecase/module/NotificationUseCaseModule.kt
  domain/usecase/notification-impl/src/main/kotlin/com/captures2024/soongan/domain/usecase/notification/impl/GetNotificationSettingsUseCaseImpl.kt
  domain/usecase/notification-impl/src/main/kotlin/com/captures2024/soongan/domain/usecase/notification/impl/PatchNotificationSettingsUseCaseImpl.kt
  domain/usecase/notification/src/main/kotlin/com/captures2024/soongan/domain/usecase/notification/GetNotificationSettingsUseCase.kt
  domain/usecase/notification/src/main/kotlin/com/captures2024/soongan/domain/usecase/notification/PatchNotificationSettingsUseCase.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/component/screen/ProfileMenuNotificationSettingScreen.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/route/ProfileMenuNotificationSettingRoute.kt
  presentation/feature/main-profile/src/main/res/values/strings.xml
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/profile/ProfileNotificationSettingViewModel.kt
Labels: enhancement

#121 [Chore] detekt CI
  .github/workflows/soongan-develop-ci.yml
  .github/workflows/soongan-pull-request-ci.yml
  build.gradle.kts
  core/common/src/main/kotlin/com/captures2024/soongan/core/common/permission/Context.kt
  data/service/api/src/main/kotlin/com/captures2024/soongan/data/service/api/NotificationsAPI.kt
  domain/usecase/notification-impl/src/main/kotlin/com/captures2024/soongan/domain/usecase/notification/impl/GetNotificationSettingsUseCaseImpl.kt
  domain/usecase/notification-impl/src/main/kotlin/com/captures2024/soongan/domain/usecase/notification/impl/PatchNotificationSettingsUseCaseImpl.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/route/ProfileMenuNotificationSettingRoute.kt
Labels: enhancement

#123 [Modify] 사용하지 않는 권한 제거
  app/src/main/AndroidManifest.xml
Labels: enhancement

#124 [Chore] firebase-app-distribution-cd
  .github/workflows/soongan-firebase-app-distribution-cd.yml
Labels: duplicate, enhancement

#125 [Bugfix] 번들 빌드 상 잘못된 부분 수정
  app/src/main/AndroidManifest.xml
  build-logic/src/main/kotlin/GoogleAuthConventionPlugin.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/awards/AwardsDetailDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/awards/GetAwardsDetailInfoResponse.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/awards/GetFirstPrizePostResponse.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/awards/GetOtherTop7PostResponse.kt
  data/service/api/src/main/kotlin/com/captures2024/soongan/data/service/api/WeeklyContestAPI.kt
  data/source/awards-impl/src/main/kotlin/com/captures2024/soongan/data/source/awards/impl/mapper/GetAwardsDetailInfoResponse.kt
  data/source/awards-impl/src/main/kotlin/com/captures2024/soongan/data/source/awards/impl/mapper/GetFirstPrizePostResponse.kt
  data/source/awards-impl/src/main/kotlin/com/captures2024/soongan/data/source/awards/impl/mapper/GetOtherTop7PostResponse.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  presentation/feature/main-awards/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/awards/component/info/AwardsInfoComponent.kt
  presentation/feature/main-awards/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/awards/component/info/AwardsInfoRoundInfoComponent.kt
  presentation/feature/main-awards/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/awards/component/screen/AwardsInfoScreen.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/award/AwardsInfoViewModel.kt
Labels: bug

#128 [Modify] feature root 모듈 분리
  app/build.gradle.kts
  app/src/main/kotlin/com/captures2024/soongan/SoonGanActivity.kt
  presentation/feature/root/build.gradle.kts
  presentation/feature/root/src/main/kotlin/com/captures2024/soongan/presentation/feature/root/component/DialogHostComponent.kt
  presentation/feature/root/src/main/kotlin/com/captures2024/soongan/presentation/feature/root/component/LoadingHostComponent.kt
  presentation/feature/root/src/main/kotlin/com/captures2024/soongan/presentation/feature/root/component/screen/AppRootScreen.kt
  presentation/feature/root/src/main/kotlin/com/captures2024/soongan/presentation/feature/root/navigation/AppNavigation.kt
  presentation/feature/root/src/main/kotlin/com/captures2024/soongan/presentation/feature/root/route/AppLandingRoute.kt
  presentation/feature/root/src/main/kotlin/com/captures2024/soongan/presentation/feature/root/route/AppMainRoute.kt
  presentation/feature/root/src/main/kotlin/com/captures2024/soongan/presentation/feature/root/route/AppRoute.kt
  presentation/feature/root/src/main/kotlin/com/captures2024/soongan/presentation/feature/root/route/AppSignRoute.kt
  presentation/feature/root/src/main/kotlin/com/captures2024/soongan/presentation/feature/root/route/DialogHost.kt
  presentation/feature/root/src/main/kotlin/com/captures2024/soongan/presentation/feature/root/route/LoadingHost.kt
  presentation/feature/root/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: refactor

#127 [SG-152] 스플래시 스크린
  presentation/feature/root/src/main/kotlin/com/captures2024/soongan/presentation/feature/root/component/screen/SplashScreen.kt
  presentation/feature/root/src/main/kotlin/com/captures2024/soongan/presentation/feature/root/route/AppLandingRoute.kt
Labels: enhancement

#133 [SG-158] 프로필 탭 알림 표시 UI 작업
  data/repository/notification-impl/src/main/kotlin/com/captures2024/soongan/data/repository/notification/impl/NotificationRepositoryImpl.kt
  data/service/api/src/main/kotlin/com/captures2024/soongan/data/service/api/NotificationsAPI.kt
  data/source/notification-impl/src/main/kotlin/com/captures2024/soongan/data/source/notification/impl/local/NotificationLocalDataSourceImpl.kt
  data/source/notification-impl/src/main/kotlin/com/captures2024/soongan/data/source/notification/impl/remote/NotificationsRemoteDataSourceImpl.kt
  data/source/notification/src/main/kotlin/com/captures2024/soongan/data/source/notification/local/NotificationLocalDataSource.kt
  data/source/notification/src/main/kotlin/com/captures2024/soongan/data/source/notification/remote/NotificationsRemoteDataSource.kt
  domain/repository/notification/src/main/kotlin/com/captures2024/soongan/domain/repository/notification/NotificationRepository.kt
  domain/usecase/module/src/main/kotlin/com/captures2024/soongan/domain/usecase/module/NotificationUseCaseModule.kt
  domain/usecase/notification-impl/src/main/kotlin/com/captures2024/soongan/domain/usecase/notification/impl/GetIsNotReadNotificationCacheFlowUseCaseImpl.kt
  domain/usecase/notification-impl/src/main/kotlin/com/captures2024/soongan/domain/usecase/notification/impl/GetUnreadNotificationsCountUseCaseImpl.kt
  domain/usecase/notification/src/main/kotlin/com/captures2024/soongan/domain/usecase/notification/GetIsNotReadNotificationCacheFlowUseCase.kt
  domain/usecase/notification/src/main/kotlin/com/captures2024/soongan/domain/usecase/notification/GetUnreadNotificationsCountUseCase.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/component/profile/ProfileTopBarComponent.kt
  presentation/feature/main-profile/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/profile/component/screen/ProfileScreen.kt
  presentation/feature/main/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/component/MainComponent.kt
  presentation/feature/main/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/component/SoonGanBottomBar.kt
  presentation/feature/main/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/component/screen/MainScreen.kt
  presentation/feature/main/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/route/MainRoute.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/MainNotificationViewModel.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/profile/ProfileNotificationViewModel.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/profile/ProfileViewModel.kt
Labels: enhancement

#134 [SG-157] 홈 API 변경 사항 반영
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/home/GetHomeStatusPostInfoResponse.kt
  data/source/home-impl/src/main/kotlin/com/captures2024/soongan/data/source/home/impl/mapper/GetHomeStatusContestInfoResponse.kt
  presentation/feature/main-home/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/home/component/home/HomeBodyNotEmptyComponent.kt
  presentation/feature/main-home/src/main/kotlin/com/captures2024/soongan/presentation/feature/main/home/route/HomeRoute.kt
  presentation/viewmodel/src/main/kotlin/com/captures2024/soongan/presentation/viewmodel/main/home/HomeViewModel.kt
Labels: enhancement
