Repository captures-2024/soongan-android, pull requests merged in 2025-04, with the labels that each got.

#81 [SG-15] 구글 로그인
  app/src/main/kotlin/com/captures2024/soongan/SoonGanActivity.kt
  build-logic/src/main/kotlin/GoogleAuthConventionPlugin.kt
  buildSrc/src/main/kotlin/DefaultKeyValue.kt
  core/auth/src/main/kotlin/com/captures2024/soongan/core/auth/AuthModule.kt
  core/auth/src/main/kotlin/com/captures2024/soongan/core/auth/GoogleApiContract.kt
  core/auth/src/main/kotlin/com/captures2024/soongan/core/auth/GoogleAuthUiClient.kt
  core/auth/src/main/kotlin/com/captures2024/soongan/core/auth/GoogleSignIn.kt
  core/network/src/main/kotlin/com/captures2024/soongan/core/network/AuthInterceptor.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/sign/SignViewModel.kt
  feature/signIn/build.gradle.kts
  feature/signIn/src/main/kotlin/com/captures2024/soongan/feature/signIn/route/SignInRoute.kt
  feature/signIn/src/main/kotlin/com/captures2024/soongan/feature/signIn/ui/SignInScreen.kt
  gradle/libs.versions.toml
  secrets.defaults.properties
Labels: refactor

#83 [feat] 네트워크 헤더 변경
  buildSrc/src/main/kotlin/DefaultKeyValue.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/remote/impl/HomeDataSourceImpl.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/remote/impl/WeeklyContestDataSourceImpl.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/service/AuthService.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/service/HomeService.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/service/MembersService.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/service/PostLikeService.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/service/ReportService.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/service/WeeklyContestService.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/AppConst.kt
  core/network/build.gradle.kts
  core/network/src/main/kotlin/com/captures2024/soongan/core/network/AuthInterceptor.kt
  secrets.defaults.properties
Labels: enhancement

#82 [refactor] navigation
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/awards/AwardsNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/feed/FeedNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/home/EditPostNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/home/HomeGalleryNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/home/HomeNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/home/HomePostNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/home/HomePostPhotoNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/home/RegistrationPostNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/profile/FAQNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/profile/NotificationNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/profile/ProfileEditNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/main/profile/ProfileNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/sign/BirthNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/sign/NicknameNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/sign/PrivacyPolicyNavigator.kt
  core/navigator/src/main/kotlin/com/captures2024/soongan/core/navigator/screen/sign/TermsOfUseNavigator.kt
  feature/sign/src/main/kotlin/com/captures2024/soongan/feature/sign/navigation/SignRouteNavhost.kt
  feature/signIn/src/main/kotlin/com/captures2024/soongan/feature/signIn/route/SignInRoute.kt
Labels: refactor

#87 [SG-113] 신고 관련 api 변경 사항 적용
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/mapper/MembersMapper.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/mapper/NotificationsMapper.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/mapper/ReportMapper.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/remote/NotificationsDataSource.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/remote/impl/NotificationsDataSourceImpl.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/MembersRepository.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/NotificationsRepository.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/ReportRepository.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/impl/MembersRepositoryImpl.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/impl/NotificationsRepositoryImpl.kt
  core/data/src/main/kotlin/com/captures2024/soongan/core/data/repository/impl/ReportRepositoryImpl.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/notifications/GetNotificationsCountUseCase.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/notifications/GetNotificationsUseCase.kt
  core/domain/src/main/kotlin/com/captures2024/soongan/core/domain/usecase/report/PostReportUseCase.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/NotificationCountDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/NotificationDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/NotificationsCountDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/NotificationsCountInfoDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/NotificationsInfoDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/ReportHistoryDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/ReportInfoDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/dto/UserInfoDto.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/mock/MockUpData.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/members/GetMemberInfoResponse.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/report/PostReportResponse.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/network/response/report/ReportHistoryResponse.kt
  core/model/src/main/kotlin/com/captures2024/soongan/core/model/utils/TypeAlias.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/home/HomeGalleryViewModel.kt
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/profile/ProfileNotificationViewModel.kt
  feature/profile/src/main/kotlin/com/captures2024/soongan/feature/profile/ui/notification/NotificationBody.kt
Labels: enhancement

#89 [SG-125] 빈 생년월일 입력 시 오류 수정
  core/viewmodel/src/main/kotlin/com/captures2024/soongan/core/viewmodel/sign/BirthViewModel.kt
Labels: bug

#90 [SG-115] PUSH Message intent parse
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/captures2024/soongan/SoonGanActivity.kt
  app/src/main/kotlin/com/captures2024/soongan/service/FirebaseCloudMessageService.kt
  gradle/libs.versions.toml
Labels: enhancement
